"""Add reasoning fields to queries table

Revision ID: 1df653d93003
Revises: 
Create Date: 2025-08-04 12:54:14.688870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df653d93003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('queries', sa.Column('execution_plan', sa.JSON(), nullable=True))
    op.add_column('queries', sa.Column('llm_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'llm_metadata')
    op.drop_column('queries', 'execution_plan')
    op.drop_column('queries', 'reasoning')
    # ### end Alembic commands ###
